'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const state=require('../project-state.js');
const block=(id,file)=>({type:'subroutineBlock',id,data:JSON.stringify({file}),fields:{NAME:id}});
const base={blocks:{blocks:[block('a','one.ts'),block('b','two.ts'),block('c','one.ts')]},variables:[{id:'v',name:'before'}]};
const live={blocks:{blocks:[{...block('a','one.ts'),fields:{NAME:'edited'}},{type:'subroutineBlock',id:'new'}]},variables:[{id:'v',name:'after'},{id:'newvar',name:'new'}]};
const result=state.mergeRegion(base,live,['a','c'],'one.ts');
assert.deepEqual(result.blocks.blocks.map(b=>b.id),['a','b','new']);
assert.equal(result.blocks.blocks[0].fields.NAME,'edited');
assert.equal(result.blocks.blocks[1].fields.NAME,'b');
assert.equal(JSON.parse(result.blocks.blocks[2].data).file,'one.ts');
assert.equal(result.variables[0].name,'after');assert.equal(result.variables.length,2);
assert.equal(base.blocks.blocks[0].fields.NAME,'a');
const rules={blocks:{blocks:[{type:'modBlock',id:'root',inputs:{RULES:{block:{type:'ruleBlock',id:'r1',next:{block:{type:'ruleBlock',id:'r2'}}}}}},block('sub','other.ts')]}};
const focused={blocks:{blocks:[{type:'ruleBlock',id:'r1',fields:{NAME:'changed'}}]}};
const merged=state.mergeFocus(rules,focused,'r1');
assert.equal(merged.blocks.blocks[0].inputs.RULES.block.fields.NAME,'changed');
assert.equal(merged.blocks.blocks[0].inputs.RULES.block.next.block.id,'r2');
assert.equal(merged.blocks.blocks[1].id,'sub');
const removed=state.mergeFocus(rules,{blocks:{blocks:[]}},'r1');
assert.equal(removed.blocks.blocks[0].inputs.RULES.block.id,'r2');
assert.throws(()=>state.mergeFocus(rules,focused,'absent'));

// Exercise the actual UI export entrypoint while only one file is visible.
const ts=require(process.env.BF6_TS||'typescript');
const source=fs.readFileSync(path.join(__dirname,'../editor_ui.js'),'utf8');
const sf=ts.createSourceFile('editor_ui.js',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
const wanted=new Set(['projectSnapshot','projectDocument','canvasSnapshot','exportAsScript','docTops','fileOfDocTop','enterRegion','writeRegionBack']);
const functions=[];
function visit(n){if(ts.isFunctionDeclaration(n)&&n.name&&wanted.has(n.name.text))functions.push(n.getText(sf));ts.forEachChild(n,visit);}visit(sf);
let compiled,sent;
const context={UI:{ws:{},doc:base,region:{file:'one.ts',topIds:['a','c']}},window:{BF6ProjectState:state,BF6Convert:{blocksToTs:doc=>{compiled=doc;return {files:{'index.ts':'export {};'}};}}},BF6:{state:{},saveWorkspace:()=>live,writeWorkspaceDoc:doc=>({mod:doc})},attachExtendedSidecar:()=>{},status:()=>{},send:msg=>{sent=msg;}};
vm.createContext(context);vm.runInContext(functions.join('\n'),context);context.exportAsScript('C:/exports');
assert.deepEqual(compiled.mod.blocks.blocks.map(b=>b.id),['a','b','new']);
assert.equal(sent.op,'exportPortalScript');
context.UI.region=null;context.UI.doc=base;context.showRegion=()=>{};context.shortFile=x=>x;
context.enterRegion('one.ts');
assert.equal(context.UI.doc.blocks.blocks[0].fields.NAME,'edited','Entering the first tab must capture unsaved all-files edits');
assert.ok(context.UI.doc.blocks.blocks.some(b=>b.id==='new'));
context.UI.ruleMode={id:'r1'};context.UI.ruleModeStash=rules;context.UI.region=null;context.BF6.saveWorkspace=()=>focused;
assert.equal(context.projectSnapshot().blocks.blocks[0].inputs.RULES.block.next.block.id,'r2');
assert.ok(context.UI.ruleMode,'Saving must not exit focused editing');
context.UI.applying=1;assert.throws(()=>context.projectSnapshot(),/finish opening/);
context.UI.applying=0;context.UI.loadingDoc=true;assert.throws(()=>context.projectSnapshot(),/finish opening/);
context.UI.loadingDoc=false;context.UI.loadFailed=true;assert.throws(()=>context.projectSnapshot(),/did not finish loading/);
console.log('Project snapshot checks passed, including first-tab edits and the actual export entrypoint.');
